[env]
outputFile = "target/x86_64-unknown-uefi/release/operating-system.efi"

[tasks.clean]
command = "rm" 
args = ["-rf", "drive"]

[tasks.clean.windows]
command = "rmdir"
args = ["\\s", "\\q", "drive"]

[tasks.compile]
command = "cargo"
args = [
	"build",
	"--target", "x86_64-unknown-uefi",
	"--release",
	"-Z", "build-std=core,compiler_builtins,alloc",
	"-Z", "build-std-features=compiler-builtins-mem"
]

[tasks.drive]
script = [
	"mkdir -p drive/EFI/BOOT",
	"cp startup.nsh drive/",
	"cp -r fonts drive/fonts",
	"cp ${outputFile} drive/EFI/BOOT/BOOTX64.efi",
]
dependencies = ["compile"]

[tasks.emulate]
description = "Creates emulated hardware to run the os on using the UEFI-bootloader."
command = "qemu-system-x86_64"
args = [
# Flags from https://gil0mendes.io/blog/an-efi-app-a-bit-rusty/
	"-nodefaults", 
	"-vga", "std", 
	"-machine", "q35", 
	"-m", "128M",
	"-drive", "if=pflash,format=raw,readonly,file=OVMF.fd",
	"-drive", "format=raw,file=fat:rw:drive",
	"-serial", "stdio", "-monitor", "vc:1024x768"
]
dependencies = ["clean", "drive"]
