[env]
disk = "./build/diskimage.dd"
parted = "parted -s ${disk} unit s"
targetArch = "x86_64"
uefiOutputFile = "target/x86_64-unknown-uefi/release/uefi-bootloader.efi"
kernelOutputFile = "target/x86_64-os/release/kernel"

qemu = 	"qemu-system-${targetArch}"

[tasks.clean]
command = "rm" 
args = ["-rf", "drive"]

[tasks.clean.windows]
command = "rmdir"
args = ["\\s", "\\q", "drive"]

[tasks.uefi]
command = "cargo"
args = [
	"build",
	"--target", "x86_64-unknown-uefi",
	"--bin", "uefi-bootloader",
	"--release",
	"-Z", "build-std=core,compiler_builtins,alloc",
	"-Z", "build-std-features=compiler-builtins-mem"
]
dependencies = ["clean"]

[tasks.kernel]
command = "cargo"
args = [
	"build",
	"--bin", "kernel",
	"--target", "x86_64-os.json",
	"--release",
	"-Z", "build-std=core,compiler_builtins,alloc",
	"-Z", "build-std-features=compiler-builtins-mem"
]
dependencies = ["clean"]

[tasks.drive]
script = [
	"mkdir -p drive/EFI/BOOT",
	"cp startup.nsh drive/",
	"cp -r fonts drive/fonts",
	"cp ${uefiOutputFile} drive/EFI/BOOT/BOOTX64.efi",
	"cp ${kernelOutputFile} drive/kernel"
]
dependencies = ["uefi", "kernel"]

[tasks.emulate]
description = "Creates emulated hardware to run the os on using the UEFI-bootloader."
command = "${qemu}"
args = [
# Flags from https://gil0mendes.io/blog/an-efi-app-a-bit-rusty/
	"-nodefaults", 
	"-vga", "std", 
	"-machine", "q35", 
	"-m", "128M",
	"-drive", "if=pflash,format=raw,readonly,file=OVMF.fd",
	"-drive", "format=raw,file=fat:rw:drive",
	"-serial", "stdio", "-monitor", "vc:1024x768"
]
dependencies = ["drive"]
