[env]
disk = "./build/diskimage.dd"
parted = "parted -s ${disk} unit s"
targetArch = "x86_64"
outputFile = "target/x86_64-unknown-uefi/debug/uefi-bootloader.efi"
qemu = 	"qemu-system-${targetArch}"

[tasks.clean]
workspace = false
command = "rm" 
args = ["-rf", "build"]

[tasks.clean.windows]
command = "rmdir"
args = ["\\s", "\\q", "build"]

[tasks.uefi]
workspace = false
command = "cargo"
args = [
	"build",
	"-p", "uefi-bootloader",
	"--target", "x86_64-unknown-uefi",
	"-Z", "build-std=core,compiler_builtins,alloc",
	"-Z", "build-std-features=compiler-builtins-mem"
]
dependencies = ["clean"]

[tasks.drive]
workspace = false
script = [
	"mkdir -p build/EFI/BOOT",
	"cp startup.nsh build/",
	"cp ${outputFile} build/EFI/BOOT/BOOTX64.efi",
]
dependencies = ["uefi"]

[tasks.emulate]
workspace = false
description = "Creates emulated hardware to run the os on using the UEFI-bootloader."
# Flags from https://gil0mendes.io/blog/an-efi-app-a-bit-rusty/
command = "${qemu}"
args = [
	"-nodefaults", 
	"-vga", "std", 
	"-machine", "q35", 
	"-m", "128M",
	"-drive", "if=pflash,format=raw,file=OVMF.fd",
	"-drive", "format=raw,file=fat:rw:build",
	"-serial", "stdio", "-monitor", "vc:1024x768"
]
dependencies = ["drive"]
