[env]
disk = "./build/diskimage.dd"
parted = "parted -s ${disk} unit s"
targetArch = "x86_64"
outputFile = "target/x86_64-unknown-uefi/debug/uefi-bootloader.efi"
qemu = 	"qemu-system-${targetArch}"

[tasks.clean]
command = "rm" 
args = ["-rf", "build"]

[tasks.clean.windows]
command = "rmdir"
args = ["\\s", "\\q", "build"]

[tasks.uefi]
command = "cargo"
args = [
	"build",
	"-p", "uefi-bootloader",
	"--target", "x86_64-unknown-uefi",
	"-Z", "build-std=core,compiler_builtins,alloc",
	"-Z", "build-std-features=compiler-builtins-mem"
]
dependencies = ["clean"]

[tasks.emulate]
description = "Creates emulated hardware to run the os on using the UEFI-bootloader."
script = [
	"mkdir -p build/EFI/BOOT",
	"cp startup.nsh build/",
	"cp ${outputFile} build/EFI/BOOT/BOOTX64.efi",

# Flags from https://gil0mendes.io/blog/an-efi-app-a-bit-rusty/
	"${qemu} -nodefaults -vga std -machine q35 -m 128M \\",
		"-drive if=pflash,format=raw,readonly,file=OVMF_CODE.fd \\",
		"-drive if=pflash,format=raw,file=OVMF_VARS-1024x768.fd \\",
		"-drive format=raw,file=fat:rw:build \\",
		"-serial stdio -monitor vc:1024x768"
]
dependencies = ["uefi"]
