%define	os_black	    0x0
%define bios_blue           0x1
%define bios_green          0x2
%define bios_cyan           0x3
%define bios_red            0x4
%define bios_purple         0x5
%define bios_brown          0x6
%define bios_gray           0x7
%define bios_darkgray       0x8
%define bios_lightblue      0x9
%define bios_lightgreen     0xA
%define bios_lightcyan      0xB
%define bios_lightred       0xC
%define bios_lightpurple    0xD
%define bios_yellow         0xE
%define bios_white          0xF
